### ISSUE TITLE
Partial function works differently in UI compared to packages

### ISSUE THREAD

**Issue by cristinamudura** [nexxbiz/JLio#44]
Using the partial function in code results in
```json
"test": [
    "=partial(@.CoverageName, @.CoveragePremiumExclTaxes, @.CoveragePremiumInclTaxes)",
    "=partial(@.CoverageName, @.CoveragePremiumExclTaxes, @.CoveragePremiumInclTaxes)"
]
```

instead of the right filterd objects, whereas in the UI the function works fine

**Comment by FransVanEk** [comment]
It seems that the packages you used were older than those used in the UI. if you upgrade the packages, the behavior will be the same
