### ISSUE TITLE
Sum, Difference function implementation request

### ISSUE THREAD

**Issue by cristinamudura** [nexxbiz/JLio#45]
We need to be able to use some functions like sum or dif give 2 different paths, or even path and value etc.

example 
```
=sum($.test, $.test1, $.test2)
```

Where Object
```json
{
    "test": "100",
    "test1" : "29.5",
    "test2": 50
}
```

As long as the path can be parsed as a number.

Same for dif
```
=dif($.test, $.test1)
```

**Comment by FransVanEk** [comment]
I will think about this. It doesn't fit the intent of the JLio concept since it is not a transformation. I will think about the definitions and the scope JLio can provide functionality.
