### ISSUE TITLE
Partial function incorrect behavior

### ISSUE THREAD

**Issue by RaulACPuscas** [nexxbiz/JLio#67]
Given the following input:
sample =
```json{
  "a": {
    "b": 1
  },
  "b": 1
}
```

Applying the following script to it:

```json
[
  {
    "path": "$.sample",
    "value": "=partial(@.a)",
    "command": "set"
  }
]
```

results in:

```json
{
  "a": {}
}
```
Applying the above script I was expecting to result in:
```json
{
  "a": {
    "b": 1
  }
}
```
as I the command is applied only on the root properties of sample object and the "$.a" will be kept unaltered.

What do you think?

**Comment by FransVanEk** [comment]
i have tested it and indeed it seems like a issue.. 

for now a workarround would be to copy it one layer more deep and filter it. after that move it back to the original position
